# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: heapster
#   namespace: kube-system
# ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: geneva.azurecr.io/heapster
        imagePullPolicy: Always
        command:
        - /run.sh
        env:
          - name: ACCOUNT
            value: "${ACCOUNT}"
        volumeMounts:
          - name: mdm-mdsd-vol
            mountPath: /tmp/geneva
            readOnly: true
          - name: secret-vol
            mountPath: /etc/mdm
            readOnly: true
      volumes:
        - name: mdm-mdsd-vol
          configMap:
            name: mdm-mdsd-conf
        - name: secret-vol
          secret:
            secretName: secret-conf
      imagePullSecrets:
        - name: genevaregistry
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     task: monitoring
#     # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
#     # If you are NOT using this as an addon, you should comment out this line.
#     kubernetes.io/cluster-service: 'true'
#     kubernetes.io/name: Heapster
#   name: heapster
#   namespace: kube-system
# spec:
#   ports:
#   - port: 80
#     targetPort: 8082
#   selector:
#     k8s-app: heapster
